/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type {
  DeleteApiLogs200,
  GetApiDbSize200,
  GetApiLogs200,
  GetApiLogsParams,
  GetApiMetricsHistory200,
  GetApiMetricsHistoryParams,
  GetApiModules200Item,
  GetApiModulesIdData200,
  GetApiModulesIdDataParams,
  GetApiStorage200,
  PostApiModulesIdConfig200,
  PostApiModulesIdConfigBody
} from './model';


/**
 * @summary List all modules
 */
export type getApiModulesResponse200 = {
  data: GetApiModules200Item[]
  status: 200
}
    
export type getApiModulesResponseSuccess = (getApiModulesResponse200) & {
  headers: Headers;
};
;

export type getApiModulesResponse = (getApiModulesResponseSuccess)

export const getGetApiModulesUrl = () => {


  

  return `http://localhost:3001/api/modules`
}

export const getApiModules = async ( options?: RequestInit): Promise<getApiModulesResponse> => {
  
  const res = await fetch(getGetApiModulesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiModulesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiModulesResponse
}



/**
 * @summary Update module sensor configuration
 */
export type postApiModulesIdConfigResponse200 = {
  data: PostApiModulesIdConfig200
  status: 200
}
    
export type postApiModulesIdConfigResponseSuccess = (postApiModulesIdConfigResponse200) & {
  headers: Headers;
};
;

export type postApiModulesIdConfigResponse = (postApiModulesIdConfigResponseSuccess)

export const getPostApiModulesIdConfigUrl = (id: string,) => {


  

  return `http://localhost:3001/api/modules/${id}/config`
}

export const postApiModulesIdConfig = async (id: string,
    postApiModulesIdConfigBody: PostApiModulesIdConfigBody, options?: RequestInit): Promise<postApiModulesIdConfigResponse> => {
  
  const res = await fetch(getPostApiModulesIdConfigUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiModulesIdConfigBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiModulesIdConfigResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiModulesIdConfigResponse
}



/**
 * @summary Get module status and time series measurements
 */
export type getApiModulesIdDataResponse200 = {
  data: GetApiModulesIdData200
  status: 200
}
    
export type getApiModulesIdDataResponseSuccess = (getApiModulesIdDataResponse200) & {
  headers: Headers;
};
;

export type getApiModulesIdDataResponse = (getApiModulesIdDataResponseSuccess)

export const getGetApiModulesIdDataUrl = (id: string,
    params?: GetApiModulesIdDataParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3001/api/modules/${id}/data?${stringifiedParams}` : `http://localhost:3001/api/modules/${id}/data`
}

export const getApiModulesIdData = async (id: string,
    params?: GetApiModulesIdDataParams, options?: RequestInit): Promise<getApiModulesIdDataResponse> => {
  
  const res = await fetch(getGetApiModulesIdDataUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiModulesIdDataResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiModulesIdDataResponse
}



/**
 * @summary Get database size
 */
export type getApiDbSizeResponse200 = {
  data: GetApiDbSize200
  status: 200
}
    
export type getApiDbSizeResponseSuccess = (getApiDbSizeResponse200) & {
  headers: Headers;
};
;

export type getApiDbSizeResponse = (getApiDbSizeResponseSuccess)

export const getGetApiDbSizeUrl = () => {


  

  return `http://localhost:3001/api/db-size`
}

export const getApiDbSize = async ( options?: RequestInit): Promise<getApiDbSizeResponse> => {
  
  const res = await fetch(getGetApiDbSizeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiDbSizeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiDbSizeResponse
}



/**
 * @summary Get system metrics history
 */
export type getApiMetricsHistoryResponse200 = {
  data: GetApiMetricsHistory200
  status: 200
}
    
export type getApiMetricsHistoryResponseSuccess = (getApiMetricsHistoryResponse200) & {
  headers: Headers;
};
;

export type getApiMetricsHistoryResponse = (getApiMetricsHistoryResponseSuccess)

export const getGetApiMetricsHistoryUrl = (params?: GetApiMetricsHistoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3001/api/metrics-history?${stringifiedParams}` : `http://localhost:3001/api/metrics-history`
}

export const getApiMetricsHistory = async (params?: GetApiMetricsHistoryParams, options?: RequestInit): Promise<getApiMetricsHistoryResponse> => {
  
  const res = await fetch(getGetApiMetricsHistoryUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiMetricsHistoryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiMetricsHistoryResponse
}



/**
 * @summary Get detailed storage information
 */
export type getApiStorageResponse200 = {
  data: GetApiStorage200
  status: 200
}
    
export type getApiStorageResponseSuccess = (getApiStorageResponse200) & {
  headers: Headers;
};
;

export type getApiStorageResponse = (getApiStorageResponseSuccess)

export const getGetApiStorageUrl = () => {


  

  return `http://localhost:3001/api/storage`
}

export const getApiStorage = async ( options?: RequestInit): Promise<getApiStorageResponse> => {
  
  const res = await fetch(getGetApiStorageUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiStorageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiStorageResponse
}



/**
 * @summary Get system logs with filtering
 */
export type getApiLogsResponse200 = {
  data: GetApiLogs200
  status: 200
}
    
export type getApiLogsResponseSuccess = (getApiLogsResponse200) & {
  headers: Headers;
};
;

export type getApiLogsResponse = (getApiLogsResponseSuccess)

export const getGetApiLogsUrl = (params?: GetApiLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3001/api/logs?${stringifiedParams}` : `http://localhost:3001/api/logs`
}

export const getApiLogs = async (params?: GetApiLogsParams, options?: RequestInit): Promise<getApiLogsResponse> => {
  
  const res = await fetch(getGetApiLogsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiLogsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiLogsResponse
}



/**
 * @summary Delete all system logs
 */
export type deleteApiLogsResponse200 = {
  data: DeleteApiLogs200
  status: 200
}
    
export type deleteApiLogsResponseSuccess = (deleteApiLogsResponse200) & {
  headers: Headers;
};
;

export type deleteApiLogsResponse = (deleteApiLogsResponseSuccess)

export const getDeleteApiLogsUrl = () => {


  

  return `http://localhost:3001/api/logs`
}

export const deleteApiLogs = async ( options?: RequestInit): Promise<deleteApiLogsResponse> => {
  
  const res = await fetch(getDeleteApiLogsUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteApiLogsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiLogsResponse
}



export type getHealthResponse200 = {
  data: void
  status: 200
}
    
export type getHealthResponseSuccess = (getHealthResponse200) & {
  headers: Headers;
};
;

export type getHealthResponse = (getHealthResponseSuccess)

export const getGetHealthUrl = () => {


  

  return `http://localhost:3001/health`
}

export const getHealth = async ( options?: RequestInit): Promise<getHealthResponse> => {
  
  const res = await fetch(getGetHealthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getHealthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getHealthResponse
}



