/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiLogsCategoryAnyOfItem } from './getApiLogsCategoryAnyOfItem';
import type { GetApiLogsLevelAnyOfItem } from './getApiLogsLevelAnyOfItem';

export type GetApiLogsParams = {
category?: 'ESP32' | 'MQTT' | 'DB' | 'API' | 'SYSTEM' | 'WEBSOCKET' | GetApiLogsCategoryAnyOfItem[];
level?: 'trace' | 'debug' | 'info' | 'warn' | 'error' | 'fatal' | GetApiLogsLevelAnyOfItem[];
search?: string;
startDate?: string;
endDate?: string;
limit?: string & number;
offset?: string & number;
};
