/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */

export type GetApiModulesTypesTypeManifest200SensorsItem = {
  key: string;
  label: string;
  unit: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  range: unknown[];
};
