/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdHistory200Co2Item } from './getApiModulesIdHistory200Co2Item';
import type { GetApiModulesIdHistory200TempItem } from './getApiModulesIdHistory200TempItem';
import type { GetApiModulesIdHistory200HumItem } from './getApiModulesIdHistory200HumItem';
import type { GetApiModulesIdHistory200VocItem } from './getApiModulesIdHistory200VocItem';
import type { GetApiModulesIdHistory200PressureItem } from './getApiModulesIdHistory200PressureItem';
import type { GetApiModulesIdHistory200TemperatureBmpItem } from './getApiModulesIdHistory200TemperatureBmpItem';

export type GetApiModulesIdHistory200 = {
  co2: GetApiModulesIdHistory200Co2Item[];
  temp: GetApiModulesIdHistory200TempItem[];
  hum: GetApiModulesIdHistory200HumItem[];
  voc: GetApiModulesIdHistory200VocItem[];
  pressure: GetApiModulesIdHistory200PressureItem[];
  temperature_bmp: GetApiModulesIdHistory200TemperatureBmpItem[];
};
