/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiStorage200MeasurementsOldestRecord } from './getApiStorage200MeasurementsOldestRecord';
import type { GetApiStorage200MeasurementsNewestRecord } from './getApiStorage200MeasurementsNewestRecord';

export type GetApiStorage200Measurements = {
  total_rows: number;
  unique_topics: number;
  /** @nullable */
  oldest_record: GetApiStorage200MeasurementsOldestRecord;
  /** @nullable */
  newest_record: GetApiStorage200MeasurementsNewestRecord;
};
