/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiLogsCategory } from './getApiLogsCategory';
import type { GetApiLogsLevel } from './getApiLogsLevel';

export type GetApiLogsParams = {
category?: GetApiLogsCategory;
level?: GetApiLogsLevel;
search?: string;
startDate?: string;
endDate?: string;
limit?: string & number;
offset?: string & number;
};
