/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiModulesIdHistory200Co2Item } from './getApiModulesIdHistory200Co2Item';
import type { GetApiModulesIdHistory200TempItem } from './getApiModulesIdHistory200TempItem';
import type { GetApiModulesIdHistory200HumItem } from './getApiModulesIdHistory200HumItem';
import type { GetApiModulesIdHistory200VocItem } from './getApiModulesIdHistory200VocItem';
import type { GetApiModulesIdHistory200PressureItem } from './getApiModulesIdHistory200PressureItem';
import type { GetApiModulesIdHistory200TemperatureBmpItem } from './getApiModulesIdHistory200TemperatureBmpItem';
import type { GetApiModulesIdHistory200Pm1Item } from './getApiModulesIdHistory200Pm1Item';
import type { GetApiModulesIdHistory200Pm25Item } from './getApiModulesIdHistory200Pm25Item';
import type { GetApiModulesIdHistory200Pm4Item } from './getApiModulesIdHistory200Pm4Item';
import type { GetApiModulesIdHistory200Pm10Item } from './getApiModulesIdHistory200Pm10Item';
import type { GetApiModulesIdHistory200Eco2Item } from './getApiModulesIdHistory200Eco2Item';
import type { GetApiModulesIdHistory200TvocItem } from './getApiModulesIdHistory200TvocItem';
import type { GetApiModulesIdHistory200TempShtItem } from './getApiModulesIdHistory200TempShtItem';
import type { GetApiModulesIdHistory200HumShtItem } from './getApiModulesIdHistory200HumShtItem';

export type GetApiModulesIdHistory200 = {
  co2: GetApiModulesIdHistory200Co2Item[];
  temp: GetApiModulesIdHistory200TempItem[];
  hum: GetApiModulesIdHistory200HumItem[];
  voc: GetApiModulesIdHistory200VocItem[];
  pressure: GetApiModulesIdHistory200PressureItem[];
  temperature_bmp: GetApiModulesIdHistory200TemperatureBmpItem[];
  pm1: GetApiModulesIdHistory200Pm1Item[];
  pm25: GetApiModulesIdHistory200Pm25Item[];
  pm4: GetApiModulesIdHistory200Pm4Item[];
  pm10: GetApiModulesIdHistory200Pm10Item[];
  eco2: GetApiModulesIdHistory200Eco2Item[];
  tvoc: GetApiModulesIdHistory200TvocItem[];
  temp_sht: GetApiModulesIdHistory200TempShtItem[];
  hum_sht: GetApiModulesIdHistory200HumShtItem[];
};
