/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiLogsHistogramCategory } from './getApiLogsHistogramCategory';
import type { GetApiLogsHistogramLevel } from './getApiLogsHistogramLevel';

export type GetApiLogsHistogramParams = {
/**
 * @pattern ^\d{4}-\d{2}-\d{2}$
 */
date: string;
category?: GetApiLogsHistogramCategory;
level?: GetApiLogsHistogramLevel;
search?: string;
};
