/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type GetApiStorage200Timescaledb = {
  total_chunks: number;
  chunks_total_size: string;
  chunks_total_size_bytes: number;
} | null;
