/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * IoT Backend API
 * API for IoT Dashboard
 * OpenAPI spec version: 1.0.0
 */

export type PostApiModulesIdResetSensorBodySensor = typeof PostApiModulesIdResetSensorBodySensor[keyof typeof PostApiModulesIdResetSensorBodySensor];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiModulesIdResetSensorBodySensor = {
  co2: 'co2',
  temp: 'temp',
  humidity: 'humidity',
  voc: 'voc',
  pressure: 'pressure',
  all: 'all',
} as const;
